version: "{build}"


#init:
#  - git config --global core.autocrlf input

# Build

os: Visual Studio 2019

build: off

clone_folder: c:\gopath\src\github.com\33cn\plugincgo

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1


# set go version
install:
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
  - set Path=C:\go116\bin;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\;%Path%
  - gcc --version
  - set GOROOT=C:\go116
  - go version
  - go env

test_script:
  - build.bat
#  - for /f "" %%G in ('go list github.com/33cn/plugin/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
