name: build
on: [push,pull_request]

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      - name: checkout
        uses: actions/checkout@v2

      - name: Intsall Golangci-lint
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u golang.org/x/tools/cmd/goimports
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.18.0
          go get -u mvdan.cc/sh/cmd/shfmt
          go get -u mvdan.cc/sh/cmd/gosh
      - name: install gcc
        run: |
          apt-get install gcc-5 g++-5
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      - name: setup pbft env
        run: |
          cd plugin/consensus/pbftlibbyz
          make install

      - name: Lint
        run: |
          make checkgofmt && make fmt_go
          # linter fail for lbyz lib not found
          # make linter
      - name: unit-test
        run: make test
      - name: coverage
        run: make coverage
      - name: cover report
        if: success()
        run: bash <(curl -s https://codecov.io/bash)


