name: build
on: [push,pull_request]

jobs:
  check_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      - name: checkout
        uses: actions/checkout@v2

      - name: Intsall Golangci-lint
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          echo $PATH
          go get -u golang.org/x/tools/cmd/goimports
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.18.0
          go get -u mvdan.cc/sh/cmd/shfmt
          go get -u mvdan.cc/sh/cmd/gosh
          make checkgofmt
          make linter
      - name: Lint
        run: |
          - make checkgofmt && make fmt_go
          - make linter
      - name: unit-test
        run: make test


